server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: simulation-service
          uri: lb://simulation-service
          predicates:
            - Path=/simulation/**
        - id: loans-service
          uri: lb://loans-service
          predicates:
            - Path=/loans/**
        - id: totalcost-service
          uri: lb://totalcost-service
          predicates:
            - Path=/totalcost/**
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users/**
        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
            - Path=/evaluation/**
        - id: tracing-service
          uri: lb://tracing-service
          predicates:
            - Path=/tracing/**